[project]
name = "pyrig-tutorial"
version = "0.1.4"
description = "Tutorial for pyrig."
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
license-files = [
  "LICENSE",
]
authors = [
  { name = "Winipedia", email = "winipedia@gmx.de" },
]
maintainers = [
  { name = "Winipedia", email = "winipedia@gmx.de" },
]
dependencies = [
  "pyrig-runtime>=3.23.61",
  "typer>=0.27.2",
]

[project.urls]
Changelog = "https://github.com/Winipedia/pyrig-tutorial/releases"
Documentation = "https://Winipedia.github.io/pyrig-tutorial"
Homepage = "https://github.com/Winipedia/pyrig-tutorial"
Issues = "https://github.com/Winipedia/pyrig-tutorial/issues"
Source = "https://github.com/Winipedia/pyrig-tutorial"

[project.scripts]
pyrig-tutorial = "pyrig_runtime.rig.cli.main:main"

[dependency-groups]
dev = [
  "actionlint-py>=1.7.12.25",
  "bandit>=1.9.4",
  "deptry>=0.25.1",
  "detect-secrets>=1.5.0",
  "mkdocstrings[python]>=1.0.6",
  "pre-commit-hooks>=6.0.0",
  "prek>=0.5.4",
  "pyflakes>=4.0.0",
  "pyrig>=18.92.1",
  "pyrig-codecov>=3.17.44",
  "pyrig-env>=1.0.41",
  "pyrig-public>=1.0.1",
  "pytest>=9.1.1",
  "pytest-cov>=7.1.0",
  "pytest-randomly>=5.0.0",
  "pytest-xdist>=3.8.0",
  "ruff>=0.16.9",
  "rumdl>=0.2.77",
  "ryl>=0.22.0",
  "shellcheck-py>=0.11.0.1",
  "shfmt-py>=4.2.0",
  "tombi>=1.5.8",
  "ty>=0.0.84",
  "typos>=1.50.3",
  "zensical>=0.0.66",
  "zizmor>=1.30.1",
]

[build-system]
requires = [
  "uv-build",
]
build-backend = "uv_build"

[tool.deptry]
root = "src"

[tool.deptry.per_rule_ignores]
DEP002 = [
  "pyrig-runtime",
]

[tool.pytest]
addopts = [
  "--cov-branch",
  "--cov-fail-under=100",
  "--cov-report=term-missing:skip-covered",
  "--cov-report=xml",
  "--cov=pyrig_tutorial",
  "--dist=worksteal",
  "--numprocesses=auto",
  "--report-chars=a",
]
filterwarnings = [
  "error",
]
strict = true
testpaths = [
  "tests",
]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
ignore = [
  "CPY001",
]
select = [
  "ALL",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
  "S101",
]

[tool.ruff.lint.pydocstyle]
convention = "google"
